"use client";
import { styled } from "@mui/material/styles";

export const Card = styled("div")({
  width: "100%",
  overflow: "hidden",
  background: "#fff",
  border: "1px solid #e8e8e8",
  transition: "all 0.2s ease",
  cursor: "pointer",
  display: "flex",
  flexDirection: "column",
  ":hover": {
    borderColor: "#aaa",
    boxShadow: "0 6px 24px rgba(0,0,0,0.09)",
    transform: "translateY(-2px)",
  },
  // Link wrapper inherits card layout
  a: {
    display: "flex",
    flexDirection: "column",
    textDecoration: "none",
    color: "inherit",
    width: "100%",
    height: "100%",
  },
});

// HEADER — fixed height, never grows
export const CardHeader = styled("div")({
  padding: "8px 12px",
  borderBottom: "1px solid #f0f0f0",
  textAlign: "center",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  height: 90,
  overflow: "hidden",
  flexShrink: 0,
  boxSizing: "border-box",
  "@media (max-width: 768px)": { height: 56, padding: "4px 6px" },
  ".vendor": {
    fontSize: 16,
    fontWeight: 700,
    color: "#111",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: 4,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
    "@media (max-width: 768px)": { fontSize: 11, letterSpacing: "0.05em", marginBottom: 2 },
  },
  ".title": {
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 1.3,
    color: "#666",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    textAlign: "center",
    maxWidth: "100%",
    "@media (max-width: 768px)": { fontSize: 10, lineHeight: 1.3, WebkitLineClamp: 2 },
  },
});

// MEDIA — fixed pixel height, image letterboxes inside (no overflow ever)
export const CardMedia = styled("div")({
  width: "100%",
  height: 320,
  flexShrink: 0,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  background: "#fff",
  overflow: "hidden",
  position: "relative",
  padding: 12,
  boxSizing: "border-box",
  "@media (max-width: 768px)": { height: 200, padding: 6 },
  img: {
    maxWidth: "100%",
    maxHeight: "100%",
    width: "auto",
    height: "auto",
    objectFit: "contain",
    objectPosition: "center",
    display: "block",
  },
  ".discount-badge": {
    position: "absolute",
    top: 10,
    left: 10,
    background: "#c41230",
    color: "white",
    padding: "4px 12px",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.05em",
    "@media (max-width: 768px)": { top: 6, left: 6, padding: "2px 6px", fontSize: 9 },
  },
});

// CONTENT — fixed height with price block + SHOP NOW button
export const CardContent = styled("div")({
  padding: "16px 16px 24px",
  borderTop: "1px solid #f0f0f0",
  display: "flex",
  flexDirection: "column",
  height: 130,
  flexShrink: 0,
  boxSizing: "border-box",
  "@media (max-width: 768px)": { padding: "12px 8px 20px", height: 100 },
  ".price-block": {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flexWrap: "nowrap",
    "@media (max-width: 768px)": { gap: 4 },
  },
  ".retail-price": {
    fontSize: 13,
    color: "#999",
    textDecoration: "line-through",
    "@media (max-width: 768px)": { fontSize: 11 },
  },
  ".wholesale-price": {
    fontSize: 18,
    fontWeight: 800,
    color: "#111",
    "@media (max-width: 768px)": { fontSize: 14 },
  },
  ".shop-now": {
    marginTop: 12,
    padding: "10px 0",
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    background: "#111",
    color: "white",
    "@media (max-width: 768px)": { marginTop: 10, padding: "8px 0", fontSize: 10 },
  },
});
