export const CardHeader = styled("div")({
  padding: "14px 12px",
  borderBottom: "1px solid #f0f0f0",
  textAlign: "center",
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "center",
  height: 90,
  overflow: "hidden",
  flexShrink: 0,
  "@media (max-width: 768px)": { height: 56, padding: "6px 6px" },
  ".vendor": {
    fontSize: 16,
    fontWeight: 700,
    color: "#111",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    marginBottom: 4,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
    "@media (max-width: 768px)": { fontSize: 11, letterSpacing: "0.05em", marginBottom: 2 },
  },
  ".title": {
    fontSize: 13,
    fontWeight: 400,
    lineHeight: 1.4,
    color: "#666",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
    textAlign: "center",
    "@media (max-width: 768px)": { fontSize: 10, lineHeight: 1.3, WebkitLineClamp: 2 },
  },
});